Web/Controllers/GenericCrudController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using Persistence;
using Persistence.Model;

namespace Web.Controllers
{
    public class PeopleController : GenericCrudController<Person>
    {
        public PeopleController(HogeContext context) : base(context) { }
    }

    public class AlcholDrinkTypesController : GenericCrudController<alchol_drink_type>
    {
        public AlcholDrinkTypesController(HogeContext context) : base(context) { }
    }

    /// <summary>
    /// 汎用 CRUD コントローラ
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public class GenericCrudController<T> : Controller
        where T : class, IEntity, new()
    {
        private readonly HogeContext _context;
        private readonly string _routeName = "Views/GenericCrud";
        private readonly string _modelName = typeof(T).Name;
        private readonly List<string> _readOnlyPropertyNames = new List<string>()
        {
            "Id",
            "Created",
            "Updated",
        };

        public GenericCrudController(HogeContext context)
        {
            _context = context;
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            base.OnActionExecuting(context);
            ViewData["ModelDisplayName"] = _modelName;
            ViewBag.ReadOnlyPropertyNames = _readOnlyPropertyNames;
        }

        // GET: {T}
        public async Task<IActionResult> Index()
        {
            var item = await _context.Set<T>().ToListAsync();
            return View($"~/{_routeName}/Index.cshtml", item);
        }

        // GET: {T}/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Set<T>()
                .SingleOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View($"~/{_routeName}/Details.cshtml", item);
        }

        // GET: {T}/Create
        public IActionResult Create()
        {
            var item = new T();
            return View($"~/{_routeName}/Create.cshtml", item);
        }

        // POST: {T}/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(T item)
        {
            if (ModelState.IsValid)
            {
                _context.Add<T>(item);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View($"~/{_routeName}/Create.cshtml", item);
        }

        // GET: {T}/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Set<T>().SingleOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View($"~/{_routeName}/Edit.cshtml", item);
        }

        // POST: {T}/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, T item)
        {
            if (id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View($"~/{_routeName}/Edit.cshtml", item);
        }

        // GET: {T}/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Set<T>()
                .SingleOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View($"~/{_routeName}/Delete.cshtml", item);
        }

        // POST: {T}/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var item = await _context.Set<T>().SingleOrDefaultAsync(m => m.Id == id);
            item.Removed = true;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ItemExists(int? id)
        {
            return _context.Set<T>().Any(e => e.Id == id);
        }
    }
}

Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Web/Views/GenericCrud/Create.cshtml
@addTagHelper "*, Web"
@{
    ViewData["Title"] = "新規作成";
    var modelDisplayName = ViewData["ModelDisplayName"];
    var readOnlyProps = ViewBag.ReadOnlyPropertyNames as List<string>;
    var props = Model.GetType().GetProperties() as IEnumerable<System.Reflection.PropertyInfo>;
    props = props
        .Where(x => !readOnlyProps.Contains(x.Name));
}

<h2>新規作成</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>@modelDisplayName</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        @foreach (var prop in props.Select(x => x.Name))
        {
            <edit asp-for="@prop"></edit>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" name="action" value="Save" class="btn btn-primary">保存</button>
                <a asp-action="Index" class="btn btn-default">一覧へ戻る</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Views/GenericCrud/Delete.cshtml
@{
    ViewData["Title"] = "削除";
    var modelDisplayName = ViewData["ModelDisplayName"];
    var props = Model.GetType().GetProperties() as IEnumerable<System.Reflection.PropertyInfo>;
}

<h2>削除</h2>

<div>
    <h4>@modelDisplayName</h4>
    <hr />
    <div class="alert alert-warning">
        <p>データを論理削除します。</p>
    </div>
    <dl class="dl -horizontal">
        @foreach (var prop in props)
        {
            <dt>
                @Html.DisplayName(prop.Name)
            </dt>
            <dd>
                @Html.Display(prop.Name)
            </dd>
        }
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="削除" class="btn btn-danger" />
            <a asp-action="Index" class="btn btn-default">一覧へ戻る</a>
        </div>
    </form>
</div>

Web/Views/GenericCrud/Details.cshtml
@{
    ViewData["Title"] = "詳細";
    var modelDisplayName = ViewData["ModelDisplayName"];
    var props = Model.GetType().GetProperties() as IEnumerable<System.Reflection.PropertyInfo>;
}

<h2>詳細</h2>

<div>
    <h4>@modelDisplayName</h4>
    <hr />
    <dl class="dl-horizontal">
        @foreach (var prop in props)
        {
            <dt>
                @Html.DisplayName(prop.Name)
            </dt>
            <dd>
                @Html.Display(prop.Name)
            </dd>
        }
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">編集</a>
    <a asp-action="Index" class="btn btn-default">一覧へ戻る</a>
</div>

Web/Views/GenericCrud/Edit.cshtml
@addTagHelper "*, Web"
@{
    ViewData["Title"] = "編集";
    var modelDisplayName = ViewData["ModelDisplayName"];
    var readOnlyProps = ViewBag.ReadOnlyPropertyNames as List<string>;
    var props = Model.GetType().GetProperties() as IEnumerable<System.Reflection.PropertyInfo>;
    props = props
        .Where(x => !readOnlyProps.Contains(x.Name));
}

<h2>編集</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>@modelDisplayName</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" for="Id" value=""/>

        @foreach (var prop in props.Select(x => x.Name))
        {
            <edit asp-for="@prop"></edit>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="変更を保存" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-default">一覧へ戻る</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Views/GenericCrud/Index.cshtml
@{
    ViewData["Title"] = "一覧";
    var modelDisplayName = ViewData["ModelDisplayName"];
    var model = (Model as IEnumerable<dynamic>).FirstOrDefault();
    var props = model?.GetType().GetProperties() as IEnumerable<System.Reflection.PropertyInfo> ?? new List<System.Reflection.PropertyInfo>();
}

<h2>一覧</h2>
<h4>@modelDisplayName</h4>

<p>
    <a asp-action="Create" class="btn btn-default">新規作成</a>
</p>
<table class="table">
    <thead>
        <tr>
            @foreach (var prop in props)
            {
                <th>
                    @prop.Name
                </th>
            }
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @foreach (var value in props.Select(x => x.GetValue(item)))
                {
                    <td>
                        @value
                    </td>
                }
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">編集</a>
                    <a asp-action="Details" asp-route-id="@item.Id">詳細</a>
                    <a asp-action="Delete" asp-route-id="@item.Id">削除</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>

<p>
    ASP.NET Core と EF Core を使ったデータ管理サイトのサンプル。<br />
    ライセンスは <a href="http://www.wtfpl.net/txt/copying/">WTFPL</a> (勝手にしてください)。
</p>

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Web/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>

    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    @*
    <environment names="Unused">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    *@
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="People" asp-action="Index">People</a></li>
                    <li><a asp-area="" asp-controller="AlcholDrinkTypes" asp-action="Index">AlcholDrinkTypes</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>2017 - <a href="https://bitbucket.org/ugai/">ugai</a></p>
        </footer>
    </div>

    <environment names="Development,Staging,Production">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    @*
    <environment names="Unused">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    *@

    @RenderSection("Scripts", required: false)
    </body>
    </html>